<?php
/**
 * Extends Storage\Pdo to interface with your database to get user and learner information
 * User: solomonliu
 * Date: 2017-03-20
 * Time: 22:58
 */

class Storage extends OAuth2\Storage\Pdo
{
    /**
     * Storage constructor. Initializes the database connection.
     */
    public function __construct()
    {
        $connection = array(
            'dsn' => 'sqlite:demo_database.sqlite', //Replace with your database connection string
            'username' => null, //Replace with the username to connect to your database
            'password' => null, //Replace with the password to connect to your database
            'options' => array()
        );
        parent::__construct($connection);
    }

    /**
     * This method should return true if the username/password combination is valid, false if the username does not exist
     * or if the username/password combination is invalid.
     *
     * @param $username string
     * @param $password string
     * @return bool true if username/password combination is valid, false if not, or username does not exist
     */
    public function checkUserCredentials($username, $password)
    {
        return parent::checkUserCredentials($username, $password); // TODO: Change the autogenerated stub
    }

    /**
     * This function should return an associative array with keys 'sub', 'name', 'preferences', and 'learners'
     *
     * @param $userId string userId to get user info for
     * @return array|bool associative array with user properties
     */
    public function getUser($userId)
    {
        return false;
    }

    /**
     * @param $username string username to look up
     * @return string|false userId userId of associated with the
     */
    public function getUserId($username) {
        return false; //TODO: query to get user id from username;
    }

    /**
     * This function should return an array of associative arrays with keys 'sub', 'name', 'gender', 'birthdate', 'preferences'
     *
     * @param $userId string userId to get learners for
     * @return array|bool array of associative arrays representing learners
     */
    private function getLearnerInfo($userId) {
        return false;
    }

    /**
     * Creates the necessary tables in the database
     */
    public function initDb() {
        $this->db->exec($this->getBuildSql());
    }

    /**
     * Set the default private key to use for JWT signing
     *
     * @param $key string default private key to use
     */
    public function setPrivateKey($key) {
        if ($this->getPrivateKey()) {
            $statement = $this->db->prepare(sprintf('UPDATE %s SET private_key = :key WHERE client_id IS NULL', $this->config['public_key_table']));
        } else {
            $statement = $this->db->prepare(sprintf('INSERT INTO %s (client_id, private_key) VALUES (NULL, :key)', $this->config['public_key_table']));
        }
        $statement->execute(array('key'=>$key));
    }
}